import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import BackgroundDecor from "@/app/components/layout/background-decor";
import Header from "@/app/components/layout/header";
import "@/styles/globals.css";

const poppins = Poppins({
    subsets: ["latin"],
    weight: ["200", "300", "400", "500", "600", "700"],
    variable: "--font-poppins",
    display: "swap",
});

export const metadata: Metadata = {
    title: "KinoLive",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${poppins.variable} antialiased`}>
                <BackgroundDecor />
                {children}
            </body>
        </html>
    );
}
